#!/usr/bin/python3.6

import boto3
import pprint

pp=pprint.pprint

ec2 = boto3.client('ec2')

response = ec2.describe_instances()

pp(response['Reservations'])

#ec2.stop_instances(InstanceIds=['i-09b7adaa25f90a78f'])#, DryRun=True)
#ec2.start_instances(InstanceIds=['i-0ded79a8290ed0c07'])#, DryRun=True)





